apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "k8s-dev-pod.fullname" . }}
  labels:
    {{- include "k8s-dev-pod.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "k8s-dev-pod.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "k8s-dev-pod.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      volumes:
      - name: home
        persistentVolumeClaim:
          claimName: {{ .Release.Name }}-home
      - name: dropbear
        persistentVolumeClaim:
          claimName: {{ .Release.Name }}-dropbear
      {{- if and .Values.authorizedKeys (not .Values.existingAuthorizedKeySecretName) }}
      - name: authorized-keys
        secret:
          secretName: {{ .Release.Name }}-authorized-keys
      {{- else if .Values.existingAuthorizedKeySecretName }}
      - name: authorized-keys
        secret:
          secretName: {{ .Values.existingAuthorizedKeySecretName }}
      {{- end }}
      {{- if .Values.volumes }}
      {{- toYaml .Values.volumes | nindent 8 }}
      {{- end }}
      {{- if .Values.tailscale.enabled }}
      serviceAccountName: "tailscale-sa"
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repo }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: PASSWORD_LOGIN_ENABLED
              value: "{{ .Values.passwordLoginEnabled }}"
            - name: NVM_INSTALL_ENABLED
              value: "{{ .Values.nvmInstallEnabled }}"
            - name: NVM_VERSION
              value: "{{ .Values.nvmVersion }}"
            - name: SDK_MAN_INSTALL_ENABLED
              value: "{{ .Values.sdkManInstallEnabled }}"
            - name: OH_MY_ZSH_INSTALL_ENABLED
              value: "{{ .Values.ohMyZshInstallEnabled }}"
            {{- if .Values.env }}
            {{- toYaml .Values.env | nindent 12 }}
            {{- end }}
          ports:
            - name: ssh
              containerPort: 3022
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: home
              mountPath: /home/developer
              readOnly: false
            - name: dropbear
              mountPath: /etc/dropbear
              readOnly: false
            {{- if or .Values.authorizedKeys .Values.existingAuthorizedKeySecretName }}
            - name: authorized-keys
              mountPath: /authorized-keys
            {{- if .Values.existingAuthorizedKeySecretName }}
              subPath: public-keys
            {{- else }}
              subPath: {{ .Values.existingAuthorizedKeySecretProperty }}
            {{- end }}
            {{- end }}
            {{- if .Values.volumeMounts }}
            {{- toYaml .Values.volumeMounts | nindent 12 }}
            {{- end }}
        {{- if .Values.tailscale.enabled }}
        - name: tailscale
          image: "{{ .Values.tailscale.image.repo }}:{{ .Values.tailscale.image.tag }}"
          imagePullPolicy: "{{ .Values.tailscale.image.pullPolicy }}"
          securityContext:
            runAsUser: 1000
            runAsGroup: 1000
          env:
            # Store the state in a k8s secret
          - name: TS_KUBE_SECRET
            value: "tailscale-state"
          - name: TS_USERSPACE
            value: "true"
          - name: TS_AUTHKEY
            valueFrom:
              secretKeyRef:
                name: tailscale-auth
                key: TS_AUTHKEY
                optional: true
        {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
