image:
  repo: ghcr.io/bryopsida/k8s-dev-pod
  tag: local
  pullPolicy: IfNotPresent
homeSize: 20
ingressEnabled: false
ingressPort: 3022
passwordLoginEnabled: true
# -- secret that is not managed by helm that holds the authorized keys property, when a value is specified this overrides using the authorizedKys
existingAuthorizedKeySecretName: ~
# existingAuthorizedKeySecretName: dev-pod-authorized-keys
# -- property on the existing secret holding the authorized keys value
existingAuthorizedKeySecretProperty: public-keys
# -- A set of authorized public keys that will be trusted for logging in as developer, when specified this will overwrite the /etc/dropbear/authorized_keys contents with the value specified here on every pod-restart
# authorizedKeys: ~
authorizedKeys: |
  ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCylR3YIlci/clTpaws1O5EthuqNQ10e8ITJ8WSPnLTcMI8N3gn33vQjda4z18LwnLEN8zGaDp+6LbnbI2A2twlNMdY2bBti8h1L+NfNvfLCuJFl1tCvYtn9mNjlj6qfwm4qOfgZY2IbvBFc9LntnJ2sBxO044qL5CeWSyibiWQdA5KdefZ055fuMozldFu9iRU1VEdpZJA6EfhCKW/z7mK26bZMJ6C9LvMaN2hfrfRtT+/FeRJrdmiMmE0Q109fkc2LT7uYE+FQTBKOaw0FS+X7PTRBdmsXlem84+Gm20pclR/cQUR4nPSljPtaSBFByAu+5+nWTdl3VCwRdLl0F7xycXQM7ZuXdSrYQjPKt2xe3iUpZ9eaVfxXPLmz6uKVvcnEfthiC6hFHrlA2i6lz2v7nO13ciBhzWwmnPox0kDqQU9MYBg/7gplLzyCXNMFv5w0S5zl5MM4o/pKY45Z3lQLfUZXsHjZYKU2ajKbDZQ1meJS+XL76QJb/N0A/oTxPM= aboyd@Andrews-MacBook-Pro.local
tailscale:
  enabled: false
  image:
    repo: ghcr.io/tailscale/tailscale
    tag: latest
    pullPolicy: Always
  authKey: ~
nvmInstallEnabled: true
nvmVersion: v0.39.7
sdkManInstallEnabled: true