image:
  repo: ghcr.io/bryopsida/k8s-dev-pod
  tag: main
  pullPolicy: Always
homeSize: 20
ingressEnabled: false
ingressPort: 3022
passwordLoginEnabled: true
tailscale:
  enabled: false
  image:
    repo: ghcr.io/tailscale/tailscale
    tag: latest
    pullPolicy: Always
  authKey: ~
