name: Lint and Test Chart

on:
  pull_request:
    paths:
      - 'charts/**'

jobs:
  test:
    name: 'Helm'
    uses: curium-rocks/flows/.github/workflows/helm-qa.yml@main
    with:
      charts_dir: 'charts'  