name: Lint and Test Charts
on:
  pull_request:
    paths:
      - 'charts/**'
concurrency:
  group: ${{ github.workflow }}-${{ github.event.number || github.ref }}
  cancel-in-progress: true
jobs:
  lint-chart:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@a12a3943b4bdde767164f792f33f40b04645d846
        with:
          fetch-depth: 0
      - name: Install Helm
        uses: azure/setup-helm@v2.1
        with:
          version: v3.7.1
      - uses: actions/setup-python@0ebf233433c08fb9061af664d501c3f3ff0e9e20
        with:
          python-version: 3.7
      - name: Install chart-testing
        uses: helm/chart-testing-action@6b64532d456fa490a3da177fbd181ac4c8192b58
        with:
          version: v3.4.0
      - name: Run lint
        run: ct lint --config .github/ct.yaml
  lint-docs:
    runs-on: ubuntu-latest
    needs: lint-chart
    steps:
      - name: Checkout
        uses: actions/checkout@a12a3943b4bdde767164f792f33f40b04645d846
      - name: Run helm-docs
        run: .github/helm-docs.sh
  kubeval-chart:
    runs-on: ubuntu-latest
    needs:
      - lint-chart
      - lint-docs
    strategy:
      matrix:
        k8s:
          - v1.18.20
          - v1.19.12
          - v1.20.8
          - v1.21.2
    steps:
      - name: Checkout
        uses: actions/checkout@a12a3943b4bdde767164f792f33f40b04645d846
        with:
          fetch-depth: 0
      - name: Run kubeval
        env:
          KUBERNETES_VERSION: ${{ matrix.k8s }}
        run: .github/kubeval.sh
  install-chart:
    name: install-chart
    runs-on: ubuntu-latest
    needs:
      - lint-chart
      - lint-docs
      - kubeval-chart
    strategy:
      matrix:
        k8s:
          - v1.18.19 
          - v1.19.11 
          - v1.20.7 
          - v1.21.2 
    steps:
      - name: Checkout
        uses: actions/checkout@a12a3943b4bdde767164f792f33f40b04645d846 
        with:
          fetch-depth: 0

      - name: Create kind ${{ matrix.k8s }} cluster
        uses: helm/kind-action@94729529f85113b88f4f819c17ce61382e6d8478 
        with:
          node_image: kindest/node:${{ matrix.k8s }}
          version: v0.11.1 

      - name: Install chart-testing
        uses: helm/chart-testing-action@6b64532d456fa490a3da177fbd181ac4c8192b58 
        with:
          version: v3.4.0 

      - name: Run chart install
        run: ct install --config .github/ct.yaml