name: Release Chart

on:
  push:
    branches:
      - main
    paths:
      - "charts/**"
      - ".github/workflows/chart-release.yml"
jobs:
  release:
    name: 'Helm'
    uses: curium-rocks/flows/.github/workflows/helm-release.yml@main
    with:
      charts_dir: charts