name: Publish Containers
on:
  schedule:
    - cron: '22 4 * * *'
  push:
    branches: [ main ]
    tags: [ 'v*.*.*' ]
    paths:
      - 'Dockerfile'
      - '.github/workflows/docker-publish.yml'
      - 'Entrypoint.sh'
  pull_request:
    branches: [ main ]
    paths:
      - 'Dockerfile'
      - '.github/workflows/docker-publish.yml'
      - 'Entrypoint.sh'
env:
  REGISTRY: ghcr.io
jobs:
  build:
    env: 
      IMAGE_NAME: bryopsida/k8s-dev-pod
      DOCKER_FILE: Dockerfile
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@dcd71f646680f2efd8db4afa5ad64fdcba30e748
      - name: Set up QEMU
        uses: docker/setup-qemu-action@master
        with:
          platforms: all
      - name: Install cosign
        if: github.event_name != 'pull_request'
        uses: sigstore/cosign-installer@536b37ec5d5b543420bdfd9b744c5965bd4d8730
        with:
          cosign-release: 'v1.4.0'
      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@79abd3f86f79a9d68a23c75a09a9a85889262adf
      - name: Log into registry ${{ env.REGISTRY }}
        if: github.event_name != 'pull_request'
        uses: docker/login-action@dd4fa0671be5250ee6f50aedf4cb05514abda2c7
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@69f6fc9d46f2f8bf0d5491e4aabe0bb8c6a4678a
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=schedule
            type=ref,event=branch
            type=ref,event=pr
            type=sha
      - name: Build and push Docker image
        id: build-and-push
        uses: docker/build-push-action@ac9327eae2b366085ac7f6a2d02df8aa8ead720a
        with:
          file: ${{ env.DOCKER_FILE }}
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          platforms: linux/amd64,linux/arm64
          labels: ${{ steps.meta.outputs.labels }}
          build-args:
            COMMIT="${{ github.sha }}"
      - name: Sign the published Docker image
        if: ${{ github.event_name != 'pull_request' }}
        env:
          COSIGN_EXPERIMENTAL: "true"
        run: cosign sign ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}@${{ steps.build-and-push.outputs.digest }}
